version: "3.9"

services:
  rabbitmq3:
    image: rabbitmq:latest
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq3:/var/lib/rabbitmq