version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
        test: rabbitmq-diagnostics -q status
        interval: 20s
        timeout: 10s
        retries: 2

  dataBase:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: easyfarming
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

  app:
    build: ./easyfarming
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATASOURCE_URL: jdbc:mysql://dataBase:3306/easyfarming?useSSL=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      PORT: 8090
    depends_on:
      - dataBase
      - rabbitmq
    ports:
      - "8090:8090"
    healthcheck:
        test: "curl http://localhost:8090"
        interval: 20s
        timeout: 10s
        retries: 2

  generator:
    build: ./generator
    depends_on:
      - rabbitmq
      - dataBase
      - app
    links:
      - rabbitmq

volumes:
  my-db: